### ISSUE TITLE
show the Factual Reporting rating for sources with a bias on the scale

### ISSUE THREAD

**Issue by lewisje** [drmikecrowe/mbfcext#1]
It's useful to distinguish The Federalist and Mother Jones, organizations with strong ideological positions but also a record of factual accuracy, from the derivative clickbait sources that don't care about getting the facts right; it might also help with the rare sources that ended up scored as Least Biased but not High on Factual Reporting (I remember one the last time I checked, but that was a few months ago).

**Comment by drmikecrowe** [comment]
Good request -- I'll add Factual Reporting to the display (somehow) in the next version

**Comment by drmikecrowe** [comment]
Factual reporting should be present in 1.0.14 of the extension
