### ISSUE TITLE
Compability with Firefox-based browsers

### ISSUE THREAD

**Issue by grahamperrin** [drmikecrowe/mbfcext#11]
At https://github.com/JeffreyATW/mbfc_icon/issues/10 (with a screenshot of Firefox) @JeffreyATW directs readers to [the extension for Chromium-based browsers](https://chrome.google.com/webstore/detail/official-media-biasfact-c/ganicjnkcddicfioohdaegodjodcbkkh). 

Re: `https://github.com/Noitidart/Chrome-Store-Foxified/issues/138` with Chrome Store Foxified `3.5`, I can add Official Media Bias/Fact Check Extension `2.0.7` to Firefox `79.0`, however it does not work as expected. 

For example: 

![image](https://user-images.githubusercontent.com/192271/89285403-2f6ec780-d648-11ea-8158-2dfbddde49e4.png)

**Comment by drmikecrowe** [comment]
I'm working on universal extension as we speak

**Comment by drmikecrowe** [comment]
Live in the add-ons store
