### ISSUE TITLE
Right-Center lean websites labeled Right in data

### ISSUE THREAD

**Issue by mirandawei** [drmikecrowe/mbfcext#13]
Thanks for making a JSON dump available, it's been extremely helpful for my group's research.

Looking through the data in `csources-pretty.json`, sites that have should lean listed as Right-Center (i.e., "b": "RC") are actually listed as Right (i.e., "b": "R"). I checked a few of the websites listed on [this page](https://mediabiasfactcheck.com/right-center/) but they are all listed as having Right lean in the data. In fact, there aren't any Right-Center sites in the data according to the JSON.

It doesn't seem to be a syncing issue, given that the data was most recently updated yesterday. Perhaps there's a typo somewhere? Thanks in advance.

**Comment by drmikecrowe** [comment]
I'm looking into this!  Sorry for the delay

**Comment by drmikecrowe** [comment]
Thanks for catching this.  This was in some new data I haven't phased into use yet, so I hadn't caught it.  All 255 are properly labeled now
