### ISSUE TITLE
Rating changes across all windows based off the current active windows rating

### ISSUE THREAD

**Issue by FrazerClews** [drmikecrowe/mbfcext#14]
I noticed a bug where the rating changes across all browser windows in the toolbar, based off what the current active windows rating is.

For example
Guardian window active
![image](https://user-images.githubusercontent.com/23621844/95694121-31e13500-0c28-11eb-89cb-ac2e8d2ac3ab.png)

Media Bias/Fact Check window active
![image](https://user-images.githubusercontent.com/23621844/95694133-3dccf700-0c28-11eb-8784-2af10d25ac76.png)

This could be a massive issue as users would see the wrong rating for a website and believe it as true when it isn't. Or use websites reporting factually correct news, and be told it has a bias or it's factually incorrect, when it isn't

**Comment by drmikecrowe** [comment]
OK, next version (coming shortly) will have this fixed.  Best I can do is ensure the icon is correct based on the current window.  When the badge changes, it changes in all windows.

**Comment by drmikecrowe** [comment]
Version 3.0.0 is now in the chrome webstore
