### ISSUE TITLE
Sites listed at MBFC website but not in extension JSON (v2)

### ISSUE THREAD

**Issue by hearvox** [drmikecrowe/mbfcext#18]
Can't find these domains in the JSON:

Domain	MBFC-pg
-------------------
24wpn.com	https://mediabiasfactcheck.com/worldpolitics-news/
kcna.kp	https://mediabiasfactcheck.com/korean-central-news-agency/
milo.yiannopoulos.net	https://mediabiasfactcheck.com/milo-news/
newschicken.com	https://mediabiasfactcheck.com/news-chicken/
npiamerica.org	https://mediabiasfactcheck.com/national-policy-institute/
oureyeonislam.com	https://mediabiasfactcheck.com/our-eye-on-islam/
patriothangout.com	https://mediabiasfactcheck.com/patriot-hangout/
proamericanews.com	https://mediabiasfactcheck.com/pro-america-news/
proud-patriots.com	https://mediabiasfactcheck.com/proud-patriots/
qpolitical.com	https://mediabiasfactcheck.com/qpolitical/
thebostontribune.com	https://mediabiasfactcheck.com/the-boston-tribune/
thebreakingnews.today	https://mediabiasfactcheck.com/thebreakingnews/
theviralpatriot.com	https://mediabiasfactcheck.com/viral-patriot/
todaydispatch.com	https://mediabiasfactcheck.com/today-dispatch/
universepolitics.com	https://mediabiasfactcheck.com/universe-politics/
usa-television.com	https://mediabiasfactcheck.com/usa-television/
usadailytime.com	https://mediabiasfactcheck.com/usa-daily-time/
worldpoliticus.com	https://mediabiasfactcheck.com/world-politicus/

**Comment by drmikecrowe** [comment]
Thanks, reported this to MBFC and asked them to update their backend.  Will close when they appear in the export
