### ISSUE TITLE
Latest csources?

### ISSUE THREAD

**Issue by hearvox** [drmikecrowe/mbfcext#20]
Mike, is this the latest list of sources?: /docs/v3/csources-pretty.json

That was updated hours ago, whereas the JSON I had been pulling, /docs/v2/csources.json (for Iffy.news, with MBFC permission), was last updated in a month ago. So wondering: What is the best file to access the latest MBFC data? Thx.

**Comment by drmikecrowe** [comment]
https://github.com/drmikecrowe/mbfcext/blob/main/docs/v3/combined.json

**Comment by drmikecrowe** [comment]
Note that there is a schema change.  That's why it went to v3

**Comment by hearvox** [comment]
Thx, Mike.
