### ISSUE TITLE
Links to the "Firefox Extension" are broken

### ISSUE THREAD

**Issue by jnton** [drmikecrowe/mbfcext#21]
Links to the _Firefox Extension_ are broken, they use [this link](https://addons.mozilla.org/en-US/firefox/addon/media-biasfact-check-extension/) but it doesn't work. The right link is [this one](https://addons.mozilla.org/en-US/firefox/addon/media-bias-fact-check/).

**Comment by drmikecrowe** [comment]
NOTE: I've updated the source but will wait until the next code change to roll out the release
