### ISSUE TITLE
Rating changes across all windows based off the current active windows rating

### ISSUE THREAD

**Issue by ColinHebert** [drmikecrowe/mbfcext#24]
This is a repeat of #14.

On 3.2.1, the rating is shared between all windows.

In the examples below you might also notice that I'm using another extension as well for [ToS;DR](https://tosdr.org/). That extension seems to be able to do reporting on the current tab as opposed to the window in focus.
The code is available on https://github.com/tosdr/browser-extensions for comparison.

Wikipedia seemingly reported as a "Conspiracy Theory/Pseudo-science" website when out of focus:
<img width="640" alt="Screen Shot 2022-01-15 at 08 55 58" src="https://user-images.githubusercontent.com/232139/149614982-fd198f9a-a226-4f71-8a60-ad7c8c280583.png">

Quackery website seemingly reported as "Least biased" when out of focus:
<img width="642" alt="Screen Shot 2022-01-15 at 08 55 49" src="https://user-images.githubusercontent.com/232139/149614978-30875270-4d08-4791-8eb8-b170a59e8e02.png">
.

**Comment by ColinHebert** [comment]
I am far from knowledgeable in this area, but looking at the differences between this extension and ToS;DR's it seems that the plugin is using "Browser Action" as opposed to "Page Action".

https://stackoverflow.com/questions/44712495/what-are-the-differences-between-page-action-and-browser-action/44713058

https://developer.chrome.com/docs/extensions/reference/browserAction/
https://developer.chrome.com/docs/extensions/reference/pageAction/

**Comment by drmikecrowe** [comment]
Thanks, let me dig into this and get back with you
