### ISSUE TITLE
Use a grayed icon for the extension when a website is not rated

### ISSUE THREAD

**Issue by ColinHebert** [drmikecrowe/mbfcext#25]
Currently the default icon for the extension when a website is not rated is a red icon (which fair enough is the icon of Media Bias/Fact Check).
This is unfortunately unnecessarily attention grabbing (colour coding suggests that red is an "attention required" type status).
It would be preferable to have the logo being greyed out (or some other indicator) when there is no information available.

**Comment by drmikecrowe** [comment]
Excellent suggestion -- let me dig into that

**Comment by drmikecrowe** [comment]
@ColinHebert -- After reviewing, I realized that the red icon (the actual MBFC red microphone) would never show. I think we need to leave it red to match the MBFC look/feel.  

Closing this for now, but if you feel strongly about this, please re-open
