### ISSUE TITLE
Sources JSON not in sync with MBFC site revision

### ISSUE THREAD

**Issue by hearvox** [drmikecrowe/mbfcext#3]
Thanks for the great extension. Invaluable in doing fake-news research.

There might be a discrepancy between the extension's data and the MBFC-site ratings. The extension has CNN.com as Factual: "Mostly Factual". While the MBFC site has revised that rating to "Mixed".
https://www.cnn.com/
https://mediabiasfactcheck.com/cnn/

That change was made a month ago:
"3/9/2020 – Based on a 5th failed fact check, CNN is moved from Mostly Factual to Mixed factual reporting"
https://mediabiasfactcheck.com/changes-corrections/

I checked several other recent revisions and the extension accurately display their MBFC changes:
/swarajya/
/southern-patriot-news/
/msnbc/

So discrepancy might be unique to CNN. Tested in both the 2.0.7 Production and Beta versions. And (what I'm guessing is) the JSON for both still lists CNN as "MF":
/docs/revised/csources.json
/docs/v2/csources.json

Happy bug hunting.

**Comment by drmikecrowe** [comment]
In theory, these are sync'd every other day.  And, the extention may cache
it for a day, so worst case scenario it could take 3d to sync.  However,
looks like there's something else systematic going on.  Checking the
source @ mbfc and will get back to you on this

**Comment by hearvox** [comment]
Stumbled upon another discrepancy. For USA Is Online, the Factual Reporting is rated Very Low: 
https://mediabiasfactcheck.com/usa-is-online/

 But `/v2/csources.json` lists no `"r": "VL"` (or any `"r"` at all):
```
"usaisonline.com": {
"b": "FN",
"d": "usaisonline.com",
"n": "USA is Online",
"P": [],
"u": "usa-is-online"
},
```

**Comment by drmikecrowe** [comment]
@hearvox -- Sorry for the delay (I missed your reply).  This is actually an issue @ MBFC -- I'll notify him
