### ISSUE TITLE
CBN shows as unrated even though it is rated

### ISSUE THREAD

**Issue by nerivera** [drmikecrowe/mbfcext#30]
### Summary
[CBN](https://www1.cbn.com/) appears to be an unrated sight, as the extension icon is the default red microphone, and clicking on the extension shows the "Not a rated sight" message. However, [the site is rated](https://mediabiasfactcheck.com/christian-broadcasting-network-cbn/).

### Steps to reproduce
1. Go to https://www1.cbn.com/
2. Note that the extension icon is the default red microphone
3. Click on the extension icon
4. Note that the popup box shows the "Not a rated site" message

### Expected Behavior
The extension icon should be the yellow "CP" icon, and the popup box should show the "Conspiracy-Pseudoscience" message.

### Device info
macOS Monterey 12.2.1
Firefox 97.0 (64-bit)
Media Bias/Fact Check Extension 3.3.0

**I did not test this on other browsers or operating systems**

**Comment by drmikecrowe** [comment]
Fixed.  Should propagate to extension within a day
