### ISSUE TITLE
Wrong bias flags for hoover.org and uproxx.com

### ISSUE THREAD

**Issue by sicin** [drmikecrowe/mbfcext#33]
hoover.org's reporting is MIXED in jsons, while on the website it's HIGH, on the other hand uproxx.com is HIGH in json, while on the website it's MIXED. I suspect there are more cases link this and it requires more investigation.

**Comment by drmikecrowe** [comment]
You might have witnessed a delay between the website update and the JSON export.  We try and export daily, but there is sometimes a delay of a few days
