### ISSUE TITLE
Schema description for json sources

### ISSUE THREAD

**Issue by jacksongoode** [drmikecrowe/mbfcext#34]
I couldn't find the interpretation of the keys in the json located [here](https://github.com/drmikecrowe/mbfcext/blob/main/docs/v4/combined.json). These are `"b", "d", "f", "n", "r", "u", "P", "c", "a", "q"`. Any help would be great!

**Comment by jacksongoode** [comment]
Found them all here (for anyone looking):
https://github.com/drmikecrowe/mbfcext/blob/main/src/utils/definitions.ts

**Comment by drmikecrowe** [comment]
@jacksongoode -- FYI, I'm experimenting with a new format:  https://github.com/drmikecrowe/mbfcext/tree/main/docs/v5

* `schema`: The json schema for each file
* `data`: The data files

This works well with https://quicktype.io/
